### ISSUE TITLE
mapping.json and curl command for update to Elasticsearch 6+

### ISSUE THREAD

**Issue by phisqb** [FUB-HCC/neonion#96]
Hi guys -

I see things are upgraded to ElasticSearch 6+. I was trying to run this and you may want to update the following:

The curl command for the mapping.json should be:
curl -XPUT "http://127.0.0.1:9200/neonion/" -H "Content-Type: application/json" -d @mapping.json

Note the -H and the double quotes. The double quotes make it work on Windows, too.

Also, I have attached an updated mapping.json file. Hopefully, it is done correctly. It seems to have worked on my machine (see below).
[mapping.zip](https://github.com/FUB-HCC/neonion/files/1616056/mapping.zip)

Thanks!

Scott

**Comment by JKatzwinkel** [comment]
Thank you very much you are absolutely right and your observation on the necessity of double quotes around the url on windows is probably useful information. The curl invocation line in `Readme.md` and update of ES index mapping has been done in 
72108f9, which was merged with pull request #97. Maybe the most convenient way to compare your modifications with those that endet up in upstream is that you push a branch or issue a pull request so everyone can have a look at the diffs at the same place?

**Comment by JKatzwinkel** [comment]
Ok nvm I just ran vimdiff and since according to [ES docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-index.html), value of `index` property defaults to `true`, our mapping files are virtually the same. Thanks for your contribution I wish I had seen it sooner!

**Comment by phisqb** [comment]
Glad I could help, Stimpson!
